name: Echo Steps - Composite with Composite

on: workflow_dispatch   

jobs:
  echo-steps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Echo Steps
        uses: ./.github/actions/echo_steps