name: .NET

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: 

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/dotnet-reusable.yml
    with:
      dotnet-version: '8.0.x'
      branches: main